### ISSUE TITLE
Spike: Uploading OpenSanctions data to wikidata

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#449]
I'm doing a spike on uploading OpenSanctions data to wikidata. Just noting down learnings and scope constraints here.

The priority right now is to be able to take one dataset of people, and make sure key biographical properties and and political positions are reflected in Wikidata. And make sure that the source of any data we upload to wikidata is usefully reflected in wikidata. 

We're going for high quality coverage of one dataset in OpenSanctions, rather than very basic coverage of all entities in opensanctions. That's because we sometimes work with teams doing a lot of research on a specific group of people, and it can be valuable to then reflect that work in Wikidata. That includes the supervised task of finding existing wikidata items, or creating ones where someone is sure they don't already exist.

## OpenSanctions data limitations

- Most names don't have a language annotation
  - generating edit proposals as if names are applicable to english for now, and letting user decide whether to accept or not. Could go into writing system/script and stuff

## Scope constraints.

- sticking to english language and assuming no language stated is english language to start with. Will probably need to improve on that soon for some datasets focusing on other scripts and so on.
- skipping properties that already have a value, rather than trying to see if we can improve on the existing value with our data.
  - except for position held [P39](https://www.wikidata.org/wiki/Property:P39) where [it's common to add the statement for each period](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Political_data_model#Holding_office_more_than_once) during which a person holds the position
- just selecting the first name alphabetically as the label, preferring labels without comma when available. 
- only creating properties for which we can give a reference (labels don't seem to take a reference. Perhaps we can put something in the edit comment?)
- only doing [reference URL (P854)](https://www.wikidata.org/wiki/Property:P854) and [retrieved (P813)](https://www.wikidata.org/wiki/Property:P813) referencing for now (see [websites](https://www.wikidata.org/wiki/Help:Sources#Web_page), [databases](https://www.wikidata.org/wiki/Help:Sources#Databases)
- Only adding given and family names for which we can find exactly one existing item, and only non-gendered given names.
  - TODO: support gendered names
  - TODO: support creating names for which items don't yet exist
  - TODO: support mutliple matching name options
    - https://www.wikidata.org/wiki/Q97065077 multiple languages
    - https://www.wikidata.org/wiki/Q97065008 Chinese
- only creating descriptions for positions tagged with gov.head, gov.executive, gov.legislative, gov.judicial - can't assume someone is a politician just because they're a PEP

## Quickstatements limitations

- ~~it looks like it can't add hour/minute precision, only date precision dates.~~ wikidata limitation with [workarounds](https://www.wikidata.org/wiki/Help:Dates#Hours,_minutes_and_seconds)
- it doesn't support multiple position held statements with distinguishing qualifiers. all the qualifiers end up on one position held statement. That's why https://github.com/everypolitician/position_statements exists

## TODO in MVP

- [x] make mypy happy
- [x] add description
- [ ] add country of citizenship
- [x] add gender
- [x] support ensuring instance of human
- [ ] support occupation (at least when the role topics are political ones, but diplomat would be nice too)
- [ ] support date of death
- [x] stop checking entities when exiting
- [x] resolve() can appear like it's hanging. do resolve() in thread or don't do next() in resolve
- [x] publish() can also appear like it's hanging

## Would be nice

- show the wikidata of already-matched items and not just the diff
- show position names of search results
- search for all the names and union the results (especially important for other writing systems)

**Comment by jbothma** [comment]
It can be nice to include date of birth in description `American politician (born 1986)`

> The description on a Wikidata entry is a short phrase designed to disambiguate [items](https://www.wikidata.org/wiki/Special:MyLanguage/Help:Items) with the same or similar [labels](https://www.wikidata.org/wiki/Special:MyLanguage/Help:Label). A [description](https://www.wikidata.org/wiki/Wikidata:Glossary#Description) does not need to be unique; multiple items can have the same description, however no two items can have both the same label and the same description.

**Comment by jbothma** [comment]
it would be nice to autmatically generate the description for any country, but for that we need the adjectival form of the nationality
(american for us, british for uk, new zealand for nz) not the demonym (american for us, briton for uk, newzealander for nz) so it's not even as simple as a sparql query.

Best would be to have library with this mapping, but let's just do a command line arg for now and do people from one country at a time.

**Comment by jbothma** [comment]
sometimes entity.get_statements(prop)[0].dataset is a str, and sometimes it's a zavod.meta.dataset.Dataset

when running with `zavod wd-up datasets/_collections/peps.yml`, sometimes the dataset name once the string form is found is `de_abgeordnetenwatch`, and sometimes it's `peps`. But we want the original source for referencing in wikidata, not the collection.

**Comment by pudo** [comment]
Refs #602

**Comment by pudo** [comment]
Closing for #602.
